### ISSUE TITLE
TACC: ERROR - could not find TLS cert for secure session

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/LLMRepository-Docker#10]
```
+ NB_SERVERDIR=/home1/07025/mosorio/MyData/.jupyter
+ mkdir -p /home1/07025/mosorio/MyData/.jupyter
+ mkdir -p /home1/07025/mosorio/.tap
+ TAP_CERTFILE=/home1/07025/mosorio/.tap/.1400897
+ '[' '!' -f /home1/07025/mosorio/.tap/.1400897 ']'
+ echo 'TACC: ERROR - could not find TLS cert for secure session'
TACC: ERROR - could not find TLS cert for secure session
++ date
```

**Comment by mosoriob** [comment]
Image must start using `tap_` Right?

**Comment by wmobley** [comment]
I'm not sure if its the image or the app name. I get really confused by this. 
Here are the comments made by the tapis team: 

Dev 1:
> But specifically regarding TAP_CERTFILE, that will only exist if the slurm job name contains the substring tap_ , as in . "tap_test"

Dev 2: 
> I see from your script that you all are also using the TAP_CERTFILE (and bailing if it doesn't exist). Does that mean that you just always ensure the job name starts with tap_ ?

Dev 1:
> Yeah exactly, if the portal detects that the app has the isInteractive: True flag set in the app's notes, it will apply that substring

**Comment by mosoriob** [comment]
The image name fixed the issue
