### ISSUE TITLE
Test docker stacks image

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/LLMRepository-Docker#19]
The building process takes a lot. can we use the docker stack images?

```
FROM jupyter/datascience-notebook:ubuntu-22.04
```

**Comment by wmobley** [comment]
I think that jupyter notebook was specific because it was configured for CUDA, which we need.

**Comment by mosoriob** [comment]
You are right. [WMA-Tapis-Templates](https://github.com/TACC/WMA-Tapis-Templates) is using the same image.

[cuda.Dockerfile](https://github.com/TACC/WMA-Tapis-Templates/blob/d6278c0bb2d799621627b3b7845acd46948aa0bf/applications/jupyter-lab-hpc/gpu/cuda.Dockerfile)
