### ISSUE TITLE
Enable continued work between session

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/LLMRepository-Docker#23]
## 🚀 Feature Request

Currently, we are downloading the repo each time. We should keep it as a single repo to allow people to work between sessions.

**Comment by mosoriob** [comment]
We need to define the directory structure. I propose to follow the structure from [jupyter-lab-hpc 1.1.0](https://github.com/TACC/WMA-Tapis-Templates/blob/main/applications/jupyter-lab-hpc/app.json)

The app defines the following directory

1. Home
2. Work
3. Scratch
4. Output

![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/3654534a-a0a1-4523-b28b-66267b4d5c13)

The directory 1, 2 and 3 are described on the following table

![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/bc389855-c088-48ff-9624-33500ed6cc71)

The output is directed to a specific location accessible through a web portal, where the TAPIS application can write it.

![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/3fb85935-e56a-47bc-b605-220a856479c0)

![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/052210fc-227c-4415-ad23-f89996f11a88)

**Comment by wmobley** [comment]
That makes sense. I think thats how its currently configured. Typically i use WORK for persistant code. And we are using SCRATCH for model and corpus I/O

**Comment by mosoriob** [comment]
Where is the best place to store the notebook?

I vote: ${WORK}

What will happen if the Git repository already exists?

I vote: Nothing, we should not overwrite the user code

**Comment by wmobley** [comment]
Yea I agree the /WORK in the container already goes to $WORK, it has lots of storage and isn't deleted

Currently we just pull the repo, to ensure the env is right but we shoudln't overwrite anything else they may have been working on.
