### ISSUE TITLE
Add jupyterlab_widgets and ipywidgets

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/LLMRepository-Docker#25]
Looks like we need to add these to base in conda. As well. 

```
conda install -n base -c conda-forge jupyterlab_widgets
conda install -n bert -c conda-forge ipywidgets
```

From @wmobley

**Comment by wmobley** [comment]
Per @mepearson 
This may be a solution as well. https://stackoverflow.com/questions/76268261/how-to-fix-when-ipywidgets-do-not-render-in-a-jupyter-lab-notbook

**Comment by mosoriob** [comment]
We don't have the `bert` environment on this image. Should be `llm`?

**Comment by mosoriob** [comment]
<img width="413" alt="image" src="https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/d0d0e579-0928-4a65-86b4-601374107101">

**Comment by wmobley** [comment]
I can't recreate the error. But despite following their instructions for getting ipywidgets new users are still seeing the error.
