### ISSUE TITLE
Notebook repository update policy

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/LLMRepository-Docker#26]
## 🚀 Feature Request

If Bob re-runs the image twice, what would be the outcome?

a. Pull the changes and update packages
b. Pull some changes (environment.yaml) and update packages
c. Nothing

**Comment by wmobley** [comment]
I think most of the time its B. 

But if we add new tutorials we would want him to have access to those as well.

**Comment by wmobley** [comment]
I initially installed the environment (lines 229 -239) after everything else and for testing just posted the URL after. However the CURL still occured before the Library install. I can't remember if doing it before that broke something or not. But, now it creates and issue as the session is ready before the environment is created and can't be used.

**Comment by mosoriob** [comment]
Good catch

**Comment by mosoriob** [comment]
> I initially installed the environment (lines 229 -239) after everything else and for testing just posted the URL after. However the CURL still occured before the Library install. I can't remember if doing it before that broke something or not. But, now it creates and issue as the session is ready before the environment is created and can't be used.

Fixed

**Comment by mosoriob** [comment]
> I think most of the time its B.
> 
> But if we add new tutorials we would want him to have access to those as wel

I recommend that we avoid updating the user's workspace automatically. Doing so can result in various side effects, such as file conflicts. Moreover, the user may not want to update a specific file, such as 'environment.yaml' or 'requirements.txt', as it may lead to the update of a package installed by the user or delete their changes on 'environment.yaml' or 'requirements.txt'.


Instead, I propose that we alert the user of an available update for the ${COOKBOOK_NAME} cookbook. To update the conda environment. The alert message will be:


```
conda env update --file ${COOKBOOK_ARCHIVE_DIR}/.binder/environment.yml --prune 
pip install --no-cache-dir -r ${COOKBOOK_ARCHIVE_DIR}/.binder/requirements.txt
```



This way, the user has the option to update the environment at their discretion.

**Comment by wmobley** [comment]
Can we run a flag to update it through app.json? The goal is to keep this simple for the end user. I want to keep them away from the command line if we can. But give them the ability to use it through jupyter if they want.

**Comment by mosoriob** [comment]
Yeah. We can do that.
