### ISSUE TITLE
model chooser dropdown box not working/appearing

### ISSUE THREAD

**Issue by kathgraves** [In-For-Disaster-Analytics/LLMRepository-Docker#49]
chooser = model_chooser() does not return a drop-down box to select llm after importing model_chooser successfully in the cell above

**Comment by mosoriob** [comment]
Notes: 

Version: https://github.com/In-For-Disaster-Analytics/sites-and-stories-nlp/commit/71900b39cb25e82fbc7ab875819a2468471ac69b

Conda packages related

```
**Apptainer> conda list  | grep widgets
ipywidgets                8.1.2              pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        3.0.10             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.10             pyhd8ed1ab_0    conda-forge
```

Lab extension
```
Apptainer> jupyter-labextension list
`sys_prefix` level settings are read-only, using `user` level for migration to `lockedExtensions`
JupyterLab v4.2.0
/usr/local/share/jupyter/labextensions
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)

```

Result

![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/4e4089d7-86a8-4741-9056-93a7b5e2f793)

**Comment by mosoriob** [comment]
LLama Index Environment (LoneStar 6) Development - 0.1.1-Pre3
Docker Image: docker://ghcr.io/in-for-disaster-analytics/tap_llmrepository-docker:sha-22610d0
Cookbook: https://github.com/In-For-Disaster-Analytics/sites-and-stories-nlp/commit/71900b39cb25e82fbc7ab875819a2468471ac69b

```
Apptainer> cd /scratch/07025/mosorio/tapis/28c40717-0bf5-4f72-bc7c-246b54da9368-007^C
Apptainer> conda list | grep widgets
ipywidgets                8.1.2              pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        3.0.10             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.10             pyhd8ed1ab_0    conda-forge
Apptainer> pip list | grep widget
ipywidgets                               8.1.2
jupyterlab_widgets                       3.0.10
widgetsnbextension                       4.0.10
Apptainer> jupyter-labextension list
`sys_prefix` level settings are read-only, using `user` level for migration to `lockedExtensions`
JupyterLab v4.2.0
/usr/local/share/jupyter/labextensions
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)

Apptainer> 







```

**Comment by mosoriob** [comment]
LLama Index Environment (LoneStar 6) Development - 0.1.1-Pre3
Docker Image: docker://ghcr.io/in-for-disaster-analytics/tap_llmrepository-docker:sha-22610d0
Cookbook: https://github.com/mosoriob/basic-jupyterlab/commit/6add8dbee4d500e7ca63ce3d58124eb64a42b66d

```
Apptainer> conda list | grep widgets
ipywidgets                8.1.2              pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        3.0.10             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.10             pyhd8ed1ab_0    conda-forge
Apptainer> pip list | grep widget
ipywidgets                8.1.2
jupyterlab_widgets        3.0.10
widgetsnbextension        4.0.10
Apptainer> jupyter-labextension list
JupyterLab v4.2.1
/work/07025/mosorio/ls6/miniconda3/envs/llm/share/jupyter/labextensions
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.10 enabled OK (python, jupyterlab_widgets)

Apptainer> 

```

![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/9693b78b-5faa-40ee-be23-8a93395c8491)

## What is the different? 

https://github.com/mosoriob/basic-jupyterlab/commit/6add8dbee4d500e7ca63ce3d58124eb64a42b66d 

- No requirements.txt
- No `ipyfilechooser==0.6.0`
- Environment.yaml light

**Comment by mosoriob** [comment]
LLama Index Environment (LoneStar 6) Development - 0.1.1-Pre3
Docker Image: docker://ghcr.io/in-for-disaster-analytics/tap_llmrepository-docker:sha-22610d0
Cookbook: https://github.com/mosoriob/basic-jupyterlab/commit/6add8dbee4d500e7ca63ce3d58124eb64a42b66d

```
Apptainer> conda list | grep widgets
ipywidgets                8.1.2              pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        3.0.10             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.10             pyhd8ed1ab_0    conda-forge
Apptainer> pip list | grep widget
ipywidgets                8.1.2
jupyterlab_widgets        3.0.10
widgetsnbextension        4.0.10
Apptainer> jupyter-labextension list
JupyterLab v4.2.1
/work/07025/mosorio/ls6/miniconda3/envs/llm/share/jupyter/labextensions
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.10 enabled OK (python, jupyterlab_widgets)

Apptainer> pip list
```

![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/711215a8-46cc-48f5-82e7-c5ab4e608b1d)


## What is the different? 

https://github.com/mosoriob/basic-jupyterlab/commit/6add8dbee4d500e7ca63ce3d58124eb64a42b66d

- No `ipyfilechooser==0.6.0`
- Environment.yaml light

**Comment by mosoriob** [comment]
LLama Index Environment (LoneStar 6) Development - 0.1.1-Pre3
Docker Image: docker://ghcr.io/in-for-disaster-analytics/tap_llmrepository-docker:sha-22610d0
Cookbook: https://github.com/mosoriob/basic-jupyterlab/commit/ada2d42f885f12202662f003706cdcda5c3849c7

```
Apptainer> conda list | grep widgets
ipywidgets                8.1.2              pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        3.0.10             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.10             pyhd8ed1ab_0    conda-forge
Apptainer> pip list | grep widget
ipywidgets                8.1.2
jupyterlab_widgets        3.0.10
widgetsnbextension        4.0.10
Apptainer> jupyter-labextension list
JupyterLab v4.2.1
/work/07025/mosorio/ls6/miniconda3/envs/llm/share/jupyter/labextensions
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.10 enabled OK (python, jupyterlab_widgets)

Apptainer> 
```

![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/711215a8-46cc-48f5-82e7-c5ab4e608b1d)


## What is the different? 


- Environment.yaml light

**Comment by mosoriob** [comment]
LLama Index Environment (LoneStar 6) Development - 0.1.1-Pre3
Docker Image: docker://ghcr.io/in-for-disaster-analytics/tap_llmrepository-docker:sha-22610d0
Cookbook: https://github.com/mosoriob/basic-jupyterlab/commit/6b07a392b0bc71c3865569f329428b67a1e9eaf0





```
Apptainer> conda list | grep widgets
ipywidgets                8.1.2              pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        3.0.10             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.10             pyhd8ed1ab_0    conda-forge
Apptainer> pip list | grep widget
ipywidgets         8.1.2
jupyterlab_widgets 3.0.10
widgetsnbextension 4.0.10
Apptainer> jupyter-labextension list
`sys_prefix` level settings are read-only, using `user` level for migration to `lockedExtensions`
JupyterLab v4.2.0
/usr/local/share/jupyter/labextensions
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)

Apptainer> 
```


![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/e4a81de2-bd6b-4418-87ca-8b3cde06d1ef)

## What is different?

- `ipykernel` is installed by conda and `jupyterlab` is installed by the Docker Image

**Comment by mosoriob** [comment]
The main difference is the path where the extensions are installed 

Working: `/work/07025/mosorio/ls6/miniconda3/envs/llm/share/jupyter/labextensions`
Not working: `/usr/local/share/jupyter/labextensions`

Why?

Working: `jupyter-lab` is installed by the user using `environment.yaml`
Not working `jupyter-lab` is installed by the Docker image

## Next steps

Remove packages installed by pip. 

> We recommend that you:
> Use pip only after conda
> Install as many requirements as possible with conda then use pip.
> 

```
# Install jupyterlab and ML packages using host cache
RUN pip install  --no-cache-dir\
    jupyterlab \
    tensorflow[and-cuda] \
    torch
```

**Comment by mosoriob** [comment]
Fixed 

[Release v0.1.1](https://ptdatax.tacc.utexas.edu/workbench/applications/jupyter-lab-llama-ls6?appVersion=0.1.1)
Please select update the conda environment to ensure dependencies are up-to-date.

**Comment by wmobley** [comment]
![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/8876497/fa879a8a-1c3f-4258-bf65-13e4bc429e8b)
I had Katherine run the image. It worked for me today. but does not work for her. See the Image.

**Comment by mosoriob** [comment]
Please share the job details

![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/56a99022-7daf-4839-a4ea-4cf02e9a109a)

**Comment by kathgraves** [comment]
I updated both the conda environment and the cookbook, and every time I
tried to run the cookbook, it would fail at the last second and I would
receive the "Failure" message. The request would submit, process, be
"Running", and then it would fail before I could open it.

**Comment by mosoriob** [comment]
I have the hypothesis that the version of Miniconda installed in @kathgraves TACC account is more up-to-date than ours. Although I'm not easily certain with the shared data.

I have released a new version. Could you try it?

https://ptdatax.tacc.utexas.edu/workbench/applications/jupyter-lab-llama-ls6?appVersion=0.1.2

Please use the parameter values shown in the screenshot below.

![image](https://github.com/In-For-Disaster-Analytics/LLMRepository-Docker/assets/2365990/79f619d9-fd3f-41d5-bc5a-8f04fca0b4e4)

**Comment by kathgraves** [comment]
I am able to get it up and running now! And the drop down model chooser is
also working!

Thank you for your help, everything looks good to go for now.
